changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies and automation
      labels:
        - dependencies
        - github_actions
    - title: Maintenance
      labels:
        - go
        - maintenance
    - title: Other changes
      labels:
        - "*"
