sonar.projectKey=SuppieRK_ccp
sonar.organization=suppierk
sonar.sources=.
sonar.exclusions=**/.git/**,**/.artifacts/**,**/testdata/**,**/*_test.go,scripts/install.sh
sonar.go.coverage.reportPaths=.artifacts/coverage/internal.cover
