package agents

import "strings"

func hookAgentTitle(agent string) string {
	if agent == "" {
		return ""
	}
	return strings.ToUpper(agent[:1]) + agent[1:]
}

func bashJSONHelpers() string {
	return `
trim_whitespace() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

json_extract_string() {
  local json="$1"
  shift
  local key marker rest char out escape
  for key in "$@"; do
    marker="\"$key\""
    [[ "$json" == *"$marker"* ]] || continue
    rest="${json#*"$marker"}"
    [[ "$rest" =~ ^[[:space:]]*:[[:space:]]*\" ]] || continue
    rest="${rest#*:}"
    while [[ "$rest" =~ ^[[:space:]] ]]; do
      rest="${rest:1}"
    done
    [[ "${rest:0:1}" == '"' ]] || continue
    rest="${rest:1}"
    out=""
    escape=0
    while ((${#rest} > 0)); do
      char="${rest:0:1}"
      rest="${rest:1}"
      if (( escape )); then
        case "$char" in
          n) out+=$'\n' ;;
          r) out+=$'\r' ;;
          t) out+=$'\t' ;;
          '"') out+="\"" ;;
          "\\") out+="\\" ;;
          /) out+="/" ;;
          *) out+="$char" ;;
        esac
        escape=0
        continue
      fi
      case "$char" in
        "\\") escape=1 ;;
        '"') printf '%s' "$out"; return 0 ;;
        *) out+="$char" ;;
      esac
    done
  done
  return 1
}

json_escape() {
  local raw="$1"
  local i char out=""
  for ((i = 0; i < ${#raw}; i++)); do
    char="${raw:i:1}"
    case "$char" in
      "\\") out+="\\\\" ;;
      '"') out+="\\\"" ;;
      $'\n') out+="\\n" ;;
      $'\r') out+="\\r" ;;
      $'\t') out+="\\t" ;;
      *) out+="$char" ;;
    esac
  done
  printf '%s' "$out"
}
`
}

func bashRewriteHelpers() string {
	return `
normalize_segment() {
  local trimmed
  trimmed="$(trim_whitespace "$1")"
  [[ -n "$trimmed" ]] || return 0
  case "$trimmed" in
    ccp|ccp\ *) printf '%s' "$trimmed" ;;
    *) printf 'ccp %s' "$trimmed" ;;
  esac
}

rewrite_command() {
  local input="$1"
  local out="" segment="" piece
  local i=0 len=${#input}
  local char next pair
  local in_single=0 in_double=0 escape=0

  while (( i < len )); do
    char="${input:i:1}"
    next="${input:i+1:1}"
    pair="${input:i:2}"

    if (( escape )); then
      segment+="$char"
      escape=0
      ((i++))
      continue
    fi
    if (( in_single )); then
      segment+="$char"
      [[ "$char" == "'" ]] && in_single=0
      ((i++))
      continue
    fi
    if (( in_double )); then
      segment+="$char"
      case "$char" in
        "\\") escape=1 ;;
        '"') in_double=0 ;;
      esac
      ((i++))
      continue
    fi

    case "$char" in
      "\\")
        segment+="$char"
        escape=1
        ((i++))
        continue
        ;;
      "'")
        segment+="$char"
        in_single=1
        ((i++))
        continue
        ;;
      '"')
        segment+="$char"
        in_double=1
        ((i++))
        continue
        ;;
    esac

    if [[ "$pair" == "&&" || "$pair" == "||" ]]; then
      piece="$(normalize_segment "$segment")"
      if [[ -n "$piece" ]]; then
        [[ -n "$out" ]] && out+=" "
        out+="$piece $pair"
      elif [[ -n "$out" ]]; then
        out+=" $pair"
      else
        out+="$pair"
      fi
      segment=""
      ((i+=2))
      while [[ "${input:i:1}" =~ [[:space:]] ]]; do
        ((i++))
      done
      continue
    fi
    if [[ "$char" == "|" || "$char" == ";" ]]; then
      piece="$(normalize_segment "$segment")"
      if [[ -n "$piece" ]]; then
        [[ -n "$out" ]] && out+=" "
        out+="$piece $char"
      elif [[ -n "$out" ]]; then
        out+=" $char"
      else
        out+="$char"
      fi
      segment=""
      ((i++))
      while [[ "${input:i:1}" =~ [[:space:]] ]]; do
        ((i++))
      done
      continue
    fi

    segment+="$char"
    ((i++))
  done

  piece="$(normalize_segment "$segment")"
  if [[ -n "$piece" ]]; then
    [[ -n "$out" ]] && out+=" "
    out+="$piece"
  fi
  printf '%s' "$out"
}
`
}

func bashRewriteHookScriptContent(agent, logFile string) string {
	return "#!/bin/bash\n" +
		"# generated by ccp init for " + agent + "\n" +
		"# " + hookAgentTitle(agent) + " PreToolUse hook: rewrite shell commands to use ccp.\n\n" +
		"LOG_FILE=\"${TMPDIR:-/tmp}/" + logFile + "\"\n\n" +
		"log_hook() {\n  printf '%s\\n' \"$1\" >>\"$LOG_FILE\"\n}\n" +
		bashJSONHelpers() +
		bashRewriteHelpers() +
		`
if ! command -v ccp >/dev/null 2>&1; then
  log_hook "skip-no-ccp"
  exit 0
fi

INPUT="$(</dev/stdin)"
if [[ -z "$INPUT" ]]; then
  log_hook "skip-empty-input"
  exit 0
fi

CMD="$(json_extract_string "$INPUT" command)"
if [[ -z "$CMD" ]]; then
  log_hook "skip-no-command"
  exit 0
fi

REWRITTEN_CMD="$(rewrite_command "$CMD")"
if [[ -z "$REWRITTEN_CMD" ]]; then
  log_hook "skip-empty-rewrite"
  exit 0
fi
if [[ "$REWRITTEN_CMD" == "$CMD" ]]; then
  log_hook "skip-no-change"
  exit 0
fi
if ! bash -n -c "$REWRITTEN_CMD" >/dev/null 2>&1; then
  log_hook "skip-invalid-shell"
  exit 0
fi

ESCAPED_CMD="$(json_escape "$REWRITTEN_CMD")"
printf '%s\n' "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"allow\",\"permissionDecisionReason\":\"ccp auto-rewrite\",\"updatedInput\":{\"command\":\"$ESCAPED_CMD\"}}}"
`
}
