package agents

import (
	"os"
	"path/filepath"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("ClineAdapter", func() {
	var (
		tmpDir    string
		scopeRoot string
		home      string
		ctx       Context
		adapter   Adapter
	)

	ginkgo.BeforeEach(func() {
		tmpDir = ginkgo.GinkgoT().TempDir()
		scopeRoot = filepath.Join(tmpDir, "repo")
		home = filepath.Join(tmpDir, "home")
		ctx = Context{ScopeRoot: scopeRoot, HomeDir: home}
		Expect(os.MkdirAll(filepath.Join(scopeRoot, ".clinerules"), 0o755)).To(Succeed())
		Expect(os.MkdirAll(home, 0o755)).To(Succeed())
		adapter = ClineAdapter{}
	})

	ginkgo.It("installs, verifies, and uninstalls its managed hook", func() {
		Expect(adapter.ID()).To(Equal("cline"))
		Expect(adapter.DetectRoot(ctx.ScopeRoot)).To(ContainSubstring(".clinerules"))

		plan := adapter.Plan(ctx)
		Expect(plan).To(HaveLen(1))
		Expect(plan[0].Path).To(HaveSuffix(filepath.Join("Cline", "Hooks", "PreToolUse")))

		_, err := adapter.Install(ctx, writeFileWriter)
		Expect(err).NotTo(HaveOccurred())
		Expect(adapter.Verify(ctx)).To(Succeed())

		res, err := adapter.(interface {
			Uninstall(Context) (InstallResult, error)
		}).Uninstall(ctx)
		Expect(err).NotTo(HaveOccurred())
		Expect(res.Applied).To(Equal(1))
	})
})

var _ = ginkgo.Describe("Cline hook execution", func() {
	type hookCase struct {
		input        string
		withCCP      bool
		wantLog      string
		wantExitCode int
		wantStdout   string
	}

	ginkgo.DescribeTable("handling runtime branches",
		func(tc hookCase) {
			result := runHookScript(ginkgo.GinkgoT(), clineHookName, "ccp-cline-hook.log", clineHookScriptContent(), tc.input, tc.withCCP)
			Expect(result.exitCode).To(Equal(tc.wantExitCode), result.stdout, result.stderr)
			if tc.wantLog != "" {
				Expect(result.log).To(ContainSubstring(tc.wantLog))
			}
			if tc.wantStdout != "" {
				Expect(result.stdout).To(ContainSubstring(tc.wantStdout))
			}
		},
		ginkgo.Entry("missing ccp", hookCase{input: `{"tool_name":"execute_command","tool_input":{"command":"pwd"}}`, wantLog: "skip-no-ccp"}),
		ginkgo.Entry("empty input", hookCase{input: "", withCCP: true, wantLog: "skip-empty-input"}),
		ginkgo.Entry("wrong tool", hookCase{input: `{"tool_name":"read_file","tool_input":{"command":"pwd"}}`, withCCP: true, wantLog: "skip-wrong-tool"}),
		ginkgo.Entry("missing command", hookCase{input: `{"tool_name":"execute_command","tool_input":{}}`, withCCP: true, wantLog: "skip-no-command"}),
		ginkgo.Entry("already prefixed", hookCase{input: `{"tool_name":"execute_command","tool_input":{"command":"ccp pwd"}}`, withCCP: true, wantLog: "skip-already-prefixed"}),
		ginkgo.Entry("blocking command execution", hookCase{input: `{"tool_name":"execute_command","tool_input":{"command":"pwd"}}`, withCCP: true, wantExitCode: 2, wantStdout: `"Decision":"block"`}),
	)
})

var _ = ginkgo.Describe("Cline hook content", func() {
	ginkgo.It("uses the canonical guidance payload", func() {
		content := clineHookScriptContent()
		for _, needle := range []string{
			"generated by ccp init for cline",
			"execute_command",
			`"Decision":"block"`,
			"Use ccp as the command prefix for shell commands",
			`LOG_FILE="${TMPDIR:-/tmp}/ccp-cline-hook.log"`,
		} {
			Expect(content).To(ContainSubstring(needle))
		}
	})
})

var _ = ginkgo.Describe("resolveClineHooksDir", func() {
	var (
		tmpDir string
		home   string
	)

	ginkgo.BeforeEach(func() {
		tmpDir = ginkgo.GinkgoT().TempDir()
		home = filepath.Join(tmpDir, "home")
	})

	ginkgo.It("prefers an existing global hooks directory", func() {
		preferred := filepath.Join(home, "Cline", "Hooks")
		Expect(os.MkdirAll(preferred, 0o755)).To(Succeed())

		Expect(resolveClineHooksDir(Context{HomeDir: home})).To(Equal(preferred))
	})

	ginkgo.It("uses the documents override when provided", func() {
		docs := filepath.Join(tmpDir, "docs")
		Expect(os.Setenv("XDG_DOCUMENTS_DIR", docs)).To(Succeed())
		ginkgo.DeferCleanup(func() {
			_ = os.Unsetenv("XDG_DOCUMENTS_DIR")
		})

		want := filepath.Join(docs, "Cline", "Hooks")
		Expect(resolveClineHooksDir(Context{HomeDir: home})).To(Equal(want))
	})
})
