package agents

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const clineHookName = "PreToolUse"

type ClineAdapter struct{}

func NewClineAdapter() ClineAdapter {
	return ClineAdapter{}
}

func (a ClineAdapter) ID() string { return string(AgentCline) }

func (a ClineAdapter) DetectRoot(scopeRoot string) string {
	return filepath.Join(scopeRoot, ".clinerules")
}

func (a ClineAdapter) Plan(ctx Context) []PlannedArtifact {
	return []PlannedArtifact{{
		Kind:    ArtifactHook,
		Path:    clineHookPath(ctx),
		Content: clineHookScriptContent(),
		Perm:    0o755,
	}}
}

func (a ClineAdapter) Install(ctx Context, write WriterFunc) (InstallResult, error) {
	changed, err := write(clineHookPath(ctx), []byte(clineHookScriptContent()), 0o755)
	if err != nil {
		return InstallResult{}, err
	}

	res := InstallResult{}
	if changed {
		res.Applied++
	} else {
		res.Noop++
	}
	return res, nil
}

func (a ClineAdapter) Verify(ctx Context) error {
	target := clineHookPath(ctx)
	data, err := os.ReadFile(target)
	if err != nil {
		return fmt.Errorf("missing cline hook file: %s", target)
	}
	content := string(data)
	for _, needle := range []string{
		"generated by ccp init for cline",
		`"Decision":"block"`,
		"Use ccp as the command prefix for shell commands",
	} {
		if !strings.Contains(content, needle) {
			return fmt.Errorf("missing cline managed hook guidance in %s", target)
		}
	}
	return nil
}

func (a ClineAdapter) Uninstall(ctx Context) (InstallResult, error) {
	removed, err := removeFileIfExists(clineHookPath(ctx))
	if err != nil {
		return InstallResult{}, err
	}
	if !removed {
		return InstallResult{Noop: 1}, nil
	}
	return InstallResult{Applied: 1}, nil
}

func clineHookPath(ctx Context) string {
	return filepath.Join(resolveClineHooksDir(ctx), clineHookName)
}

func resolveClineHooksDir(ctx Context) string {
	home := strings.TrimSpace(ctx.HomeDir)
	candidates := make([]string, 0, 5)
	if docs := strings.TrimSpace(os.Getenv("XDG_DOCUMENTS_DIR")); docs != "" {
		candidates = append(candidates, filepath.Join(docs, "Cline", "Hooks"))
	}
	if home != "" {
		candidates = append(candidates,
			filepath.Join(home, "Documents", "Cline", "Hooks"),
			filepath.Join(home, "Documents", "Cline", "Rules", "Hooks"),
			filepath.Join(home, "Cline", "Hooks"),
			filepath.Join(home, "Cline", "Rules", "Hooks"),
		)
	}
	for _, candidate := range dedupeStrings(candidates) {
		if st, err := os.Stat(candidate); err == nil && st.IsDir() {
			return candidate
		}
	}
	if len(candidates) > 0 {
		return candidates[0]
	}
	return filepath.Join("Cline", "Hooks")
}

func dedupeStrings(items []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if _, ok := seen[item]; ok || item == "" {
			continue
		}
		seen[item] = struct{}{}
		out = append(out, item)
	}
	return out
}

func clineHookScriptContent() string {
	return bashBlockingHookScriptContent(
		"cline",
		"Cline PreToolUse hook: enforce the ccp prefix before execute_command runs.",
		"ccp-cline-hook.log",
		"execute_command",
		"command",
		`printf '{"Decision":"block","Reason":"Use ccp as the command prefix for shell commands. Retry as: ccp %s"}\n' "$CMD"`,
	)
}
