package agents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClineAdapterInstallVerifyAndUninstall(t *testing.T) {
	tmp := t.TempDir()
	scopeRoot := filepath.Join(tmp, "repo")
	home := filepath.Join(tmp, "home")
	ctx := Context{ScopeRoot: scopeRoot, HomeDir: home}
	if err := os.MkdirAll(filepath.Join(scopeRoot, ".clinerules"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(home, 0o755); err != nil {
		t.Fatal(err)
	}
	a := NewClineAdapter()
	if a.ID() != "cline" {
		t.Fatalf(errUnexpectedIDFmt, a.ID())
	}
	if !strings.Contains(a.DetectRoot(ctx.ScopeRoot), ".clinerules") {
		t.Fatalf(errUnexpectedRootFmt, a.DetectRoot(ctx.ScopeRoot))
	}
	plan := a.Plan(ctx)
	if len(plan) != 1 || !strings.HasSuffix(plan[0].Path, filepath.Join("Cline", "Hooks", "PreToolUse")) {
		t.Fatalf("unexpected plan: %+v", plan)
	}
	if _, err := a.Install(ctx, writeFileWriter); err != nil {
		t.Fatalf(errInstallFmt, err)
	}
	if err := a.Verify(ctx); err != nil {
		t.Fatalf(errVerifyFmt, err)
	}
	res, err := a.Uninstall(ctx)
	if err != nil || res.Applied != 1 {
		t.Fatalf(errUnexpectedUninstFmt, res, err)
	}
}

func TestClineHookScriptExecutesExpectedBranches(t *testing.T) {
	tests := []struct {
		name         string
		input        string
		withCCP      bool
		wantLog      string
		wantExitCode int
		wantStdout   string
	}{
		{name: "missing ccp", input: `{"tool_name":"execute_command","tool_input":{"command":"pwd"}}`, wantLog: "skip-no-ccp"},
		{name: "empty input", input: "", withCCP: true, wantLog: "skip-empty-input"},
		{name: "wrong tool", input: `{"tool_name":"read_file","tool_input":{"command":"pwd"}}`, withCCP: true, wantLog: "skip-wrong-tool"},
		{name: "missing command", input: `{"tool_name":"execute_command","tool_input":{}}`, withCCP: true, wantLog: "skip-no-command"},
		{name: "already prefixed", input: `{"tool_name":"execute_command","tool_input":{"command":"ccp pwd"}}`, withCCP: true, wantLog: "skip-already-prefixed"},
		{name: "block", input: `{"tool_name":"execute_command","tool_input":{"command":"pwd"}}`, withCCP: true, wantExitCode: 2, wantStdout: `"Decision":"block"`},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result := runHookScript(t, clineHookName, "ccp-cline-hook.log", clineHookScriptContent(), tc.input, tc.withCCP)
			if result.exitCode != tc.wantExitCode {
				t.Fatalf("expected cline exit code %d, got %d stdout=%q stderr=%q", tc.wantExitCode, result.exitCode, result.stdout, result.stderr)
			}
			if tc.wantLog != "" && !strings.Contains(result.log, tc.wantLog) {
				t.Fatalf("expected log marker %q, got %q", tc.wantLog, result.log)
			}
			if tc.wantStdout != "" && !strings.Contains(result.stdout, tc.wantStdout) {
				t.Fatalf("expected stdout to contain %q, got %q", tc.wantStdout, result.stdout)
			}
		})
	}
}

func TestClineRuleContentUsesCanonicalGuidance(t *testing.T) {
	content := clineHookScriptContent()
	for _, needle := range []string{
		"generated by ccp init for cline",
		"execute_command",
		`"Decision":"block"`,
		"Use ccp as the command prefix for shell commands",
		`LOG_FILE="${TMPDIR:-/tmp}/ccp-cline-hook.log"`,
	} {
		if !strings.Contains(content, needle) {
			t.Fatalf("expected canonical cline hook content %q, got: %s", needle, content)
		}
	}
}

func TestResolveClineHooksDirPrefersExistingGlobalDirectory(t *testing.T) {
	tmp := t.TempDir()
	home := filepath.Join(tmp, "home")
	preferred := filepath.Join(home, "Cline", "Hooks")
	if err := os.MkdirAll(preferred, 0o755); err != nil {
		t.Fatal(err)
	}
	got := resolveClineHooksDir(Context{HomeDir: home})
	if got != preferred {
		t.Fatalf("expected existing hooks dir %s, got %s", preferred, got)
	}
}

func TestResolveClineHooksDirUsesDocumentsOverride(t *testing.T) {
	tmp := t.TempDir()
	home := filepath.Join(tmp, "home")
	docs := filepath.Join(tmp, "docs")
	t.Setenv("XDG_DOCUMENTS_DIR", docs)
	got := resolveClineHooksDir(Context{HomeDir: home})
	want := filepath.Join(docs, "Cline", "Hooks")
	if got != want {
		t.Fatalf("expected documents override %s, got %s", want, got)
	}
}
