package agents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodeBuddyAdapterInstallVerifyAndUninstall(t *testing.T) {
	tmp := t.TempDir()
	scopeRoot := filepath.Join(tmp, "repo")
	home := filepath.Join(tmp, "home")
	ctx := Context{ScopeRoot: scopeRoot, HomeDir: home}
	if err := os.MkdirAll(filepath.Join(scopeRoot, ".codebuddy"), 0o755); err != nil {
		t.Fatal(err)
	}
	a := NewCodeBuddyAdapter()
	if a.ID() != "codebuddy" {
		t.Fatalf(errUnexpectedIDFmt, a.ID())
	}
	if !strings.Contains(a.DetectRoot(ctx.ScopeRoot), ".codebuddy") {
		t.Fatalf(errUnexpectedRootFmt, a.DetectRoot(ctx.ScopeRoot))
	}
	plan := a.Plan(ctx)
	if len(plan) != 2 || !strings.HasSuffix(plan[0].Path, filepath.Join(".codebuddy", "hooks", codebuddyHookScriptName)) || !strings.HasSuffix(plan[1].Path, filepath.Join(".codebuddy", codebuddySettingsName)) {
		t.Fatalf("unexpected plan: %+v", plan)
	}
	if _, err := a.Install(ctx, writeFileWriter); err != nil {
		t.Fatalf(errInstallFmt, err)
	}
	if err := a.Verify(ctx); err != nil {
		t.Fatalf(errVerifyFmt, err)
	}
	res, err := a.Uninstall(ctx)
	if err != nil || res.Applied != 2 {
		t.Fatalf(errUnexpectedUninstFmt, res, err)
	}
}

func TestCodeBuddySettingsUseHook(t *testing.T) {
	tmp := t.TempDir()
	settings := filepath.Join(tmp, codebuddySettingsName)
	hook := filepath.Join(tmp, codebuddyHookScriptName)
	escapedHook := strings.ReplaceAll(hook, "\\", "\\\\")
	content := "{\n  \"hooks\": {\n    \"PreToolUse\": [\n      {\n        \"matcher\": \"Bash\",\n        \"hooks\": [\n          {\n            \"type\": \"command\",\n            \"command\": \"" + escapedHook + "\"\n          }\n        ]\n      }\n    ]\n  }\n}\n"
	if err := os.WriteFile(settings, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	ok, err := codebuddySettingsUseHook(settings, hook)
	if err != nil || !ok {
		t.Fatalf("expected settings to contain managed hook, ok=%v err=%v", ok, err)
	}
}

func TestCodeBuddyHookScriptExecutesExpectedBranches(t *testing.T) {
	tests := []struct {
		name         string
		input        string
		withCCP      bool
		wantLog      string
		wantCommand  string
		wantNoOutput bool
	}{
		{name: "missing ccp", input: `{"tool_input":{"command":"pwd"}}`, wantLog: "skip-no-ccp", wantNoOutput: true},
		{name: "empty input", input: "", withCCP: true, wantLog: "skip-empty-input", wantNoOutput: true},
		{name: "missing command", input: `{"tool_input":{}}`, withCCP: true, wantLog: "skip-no-command", wantNoOutput: true},
		{name: "already prefixed", input: `{"tool_input":{"command":"ccp pwd"}}`, withCCP: true, wantLog: "skip-no-change", wantNoOutput: true},
		{name: "rewrite", input: `{"tool_input":{"command":"pwd && ls"}}`, withCCP: true, wantCommand: "ccp pwd && ccp ls"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result := runHookScript(t, codebuddyHookScriptName, "ccp-codebuddy-hook.log", codebuddyHookScriptContent(), tc.input, tc.withCCP)
			if result.exitCode != 0 {
				t.Fatalf("expected codebuddy hook exit 0, got %d stderr=%q", result.exitCode, result.stderr)
			}
			if tc.wantLog != "" && !strings.Contains(result.log, tc.wantLog) {
				t.Fatalf("expected log marker %q, got %q", tc.wantLog, result.log)
			}
			if tc.wantNoOutput {
				if strings.TrimSpace(result.stdout) != "" {
					t.Fatalf("expected no output, got %q", result.stdout)
				}
				return
			}
			if got := decodeClaudeHookOutput(t, result.stdout); got != tc.wantCommand {
				t.Fatalf("expected rewritten command %q, got %q", tc.wantCommand, got)
			}
		})
	}
}

func TestCodeBuddyRuleContentUsesCanonicalGuidance(t *testing.T) {
	content := codebuddyHookScriptContent()
	for _, needle := range []string{
		"generated by ccp init for codebuddy",
		"rewrite shell commands to use ccp",
		"ccp auto-rewrite",
		`LOG_FILE="${TMPDIR:-/tmp}/ccp-codebuddy-hook.log"`,
	} {
		if !strings.Contains(content, needle) {
			t.Fatalf("expected canonical codebuddy hook content %q, got: %s", needle, content)
		}
	}
}
