package agents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestContinueAdapterInstallVerifyAndUninstall(t *testing.T) {
	tmp := t.TempDir()
	scopeRoot := filepath.Join(tmp, "repo")
	home := filepath.Join(tmp, "home")
	ctx := Context{ScopeRoot: scopeRoot, HomeDir: home}
	if err := os.MkdirAll(filepath.Join(scopeRoot, ".continue"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(home, 0o755); err != nil {
		t.Fatal(err)
	}
	a := NewContinueAdapter()
	if a.ID() != "continue" {
		t.Fatalf(errUnexpectedIDFmt, a.ID())
	}
	if !strings.Contains(a.DetectRoot(ctx.ScopeRoot), ".continue") {
		t.Fatalf(errUnexpectedRootFmt, a.DetectRoot(ctx.ScopeRoot))
	}
	plan := a.Plan(ctx)
	if len(plan) != 2 || !strings.HasSuffix(plan[0].Path, filepath.Join(".continue", "hooks", "ccp-rewrite.sh")) || !strings.HasSuffix(plan[1].Path, filepath.Join(".continue", "settings.json")) {
		t.Fatalf("unexpected plan: %+v", plan)
	}
	if _, err := a.Install(ctx, writeFileWriter); err != nil {
		t.Fatalf(errInstallFmt, err)
	}
	if err := a.Verify(ctx); err != nil {
		t.Fatalf(errVerifyFmt, err)
	}
	res, err := a.Uninstall(ctx)
	if err != nil || res.Applied != 2 {
		t.Fatalf(errUnexpectedUninstFmt, res, err)
	}
}

func TestContinueHookScriptExecutesExpectedBranches(t *testing.T) {
	tests := []struct {
		name         string
		input        string
		withCCP      bool
		wantLog      string
		wantCommand  string
		wantNoOutput bool
	}{
		{name: "missing ccp", input: `{"tool_input":{"command":"pwd"}}`, wantLog: "skip-no-ccp", wantNoOutput: true},
		{name: "empty input", input: "", withCCP: true, wantLog: "skip-empty-input", wantNoOutput: true},
		{name: "missing command", input: `{"tool_input":{}}`, withCCP: true, wantLog: "skip-no-command", wantNoOutput: true},
		{name: "already prefixed", input: `{"tool_input":{"command":"ccp pwd"}}`, withCCP: true, wantLog: "skip-no-change", wantNoOutput: true},
		{name: "rewrite", input: `{"tool_input":{"command":"pwd && ls"}}`, withCCP: true, wantCommand: "ccp pwd && ccp ls"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result := runHookScript(t, continueHookScriptName, "ccp-continue-hook.log", continueHookScriptContent(), tc.input, tc.withCCP)
			if result.exitCode != 0 {
				t.Fatalf("expected continue hook exit 0, got %d stderr=%q", result.exitCode, result.stderr)
			}
			if tc.wantLog != "" && !strings.Contains(result.log, tc.wantLog) {
				t.Fatalf("expected log marker %q, got %q", tc.wantLog, result.log)
			}
			if tc.wantNoOutput {
				if strings.TrimSpace(result.stdout) != "" {
					t.Fatalf("expected no output, got %q", result.stdout)
				}
				return
			}
			if got := decodeClaudeHookOutput(t, result.stdout); got != tc.wantCommand {
				t.Fatalf("expected rewritten command %q, got %q", tc.wantCommand, got)
			}
		})
	}
}

func TestContinueRuleContentUsesCanonicalGuidance(t *testing.T) {
	content := continueHookScriptContent()
	for _, needle := range []string{
		"generated by ccp init for continue",
		"rewrite shell commands to use ccp",
		"ccp auto-rewrite",
		`LOG_FILE="${TMPDIR:-/tmp}/ccp-continue-hook.log"`,
	} {
		if !strings.Contains(content, needle) {
			t.Fatalf("expected canonical continue hook content %q, got: %s", needle, content)
		}
	}
}
