package agents

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type GenericAdapter struct {
	id      string
	rootDir string
}

func NewGenericAdapter(id, rootDir string) GenericAdapter {
	return GenericAdapter{id: id, rootDir: rootDir}
}

func (a GenericAdapter) ID() string { return a.id }
func (a GenericAdapter) DetectRoot(scopeRoot string) string {
	return filepath.Join(scopeRoot, a.rootDir)
}

func (a GenericAdapter) Plan(ctx Context) []PlannedArtifact {
	root := a.DetectRoot(ctx.ScopeRoot)
	hookPath := filepath.Join(root, "hooks", "ccp-rewrite.sh")
	settingsPath := filepath.Join(root, "settings.json")
	awarenessPath := filepath.Join(root, "CCP.md")
	escapedHookPath := strings.ReplaceAll(hookPath, "\\", "\\\\")
	return []PlannedArtifact{
		{
			Kind:    ArtifactHook,
			Path:    hookPath,
			Content: fmt.Sprintf("#!/usr/bin/env sh\n# generated by ccp init for %s\n# rewrite placeholder: command-proxy hook entry\nexec ccp \"$@\"\n", a.id),
			Perm:    0o755,
		},
		{
			Kind:    ArtifactSettings,
			Path:    settingsPath,
			Content: fmt.Sprintf("{\n  \"ccp\": {\n    \"rewriteHook\": \"%s\"\n  }\n}\n", escapedHookPath),
			Perm:    0o644,
		},
		{
			Kind:    ArtifactAwareness,
			Path:    awarenessPath,
			Content: awarenessContent(a.id),
			Perm:    0o644,
		},
	}
}

func (a GenericAdapter) Install(ctx Context, write WriterFunc) (InstallResult, error) {
	return InstallPlannedArtifacts(a.Plan(ctx), write)
}

func (a GenericAdapter) Verify(ctx Context) error {
	root := a.DetectRoot(ctx.ScopeRoot)
	for _, check := range []struct {
		path string
		msg  string
	}{
		{path: filepath.Join(root, "hooks", "ccp-rewrite.sh"), msg: "missing hook script: %s"},
		{path: filepath.Join(root, "settings.json"), msg: "missing settings file: %s"},
		{path: filepath.Join(root, "CCP.md"), msg: "missing awareness file: %s"},
	} {
		if _, err := os.Stat(check.path); err != nil {
			return fmt.Errorf(check.msg, check.path)
		}
	}
	return nil
}

func awarenessContent(toolID string) string {
	return fmt.Sprintf("# CCP Proxy Integration\n\nTool: %s\n\nCommands are routed through `ccp` via hook wiring installed by `ccp init`.\n", toolID)
}
