package agents

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("hook settings family", func() {
	type hookScript struct {
		name       string
		scriptName string
		logName    string
		content    string
	}

	type hookCase struct {
		input        string
		withCmdshape bool
		wantLog      string
		wantCommand  string
		wantNoOutput bool
	}

	ginkgo.DescribeTable("resolving managed hook roots",
		func(ctx Context, rel []string, expected string) {
			Expect(homeOrScopePath(ctx, rel...)).To(Equal(expected))
		},
		ginkgo.Entry("prefers the home directory when present", Context{HomeDir: "home", ScopeRoot: "repo"}, []string{".codebuddy", "settings.json"}, filepath.Join("home", ".codebuddy", "settings.json")),
		ginkgo.Entry("falls back to the scope root when home is empty", Context{ScopeRoot: "repo"}, []string{".codebuddy", "settings.json"}, filepath.Join("repo", ".codebuddy", "settings.json")),
	)

	ginkgo.DescribeTable("rendering canonical hook guidance",
		func(name string, content string, needles []string) {
			for _, needle := range needles {
				Expect(content).To(ContainSubstring(needle), name)
			}
		},
		ginkgo.Entry("codebuddy", "codebuddy", bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log"), []string{
			"generated by cmdshape init for codebuddy",
			"rewrite shell commands to use cmdshape",
			"cmdshape auto-rewrite",
			`LOG_FILE="${TMPDIR:-/tmp}/cmdshape-codebuddy-hook.log"`,
		}),
	)

	ginkgo.DescribeTable("executing managed hook scripts",
		func(script hookScript, tc hookCase) {
			result := runHookScript(ginkgo.GinkgoT(), script.scriptName, script.logName, script.content, tc.input, tc.withCmdshape)
			Expect(result.exitCode).To(Equal(0), result.stderr)

			if tc.wantLog != "" {
				Expect(result.log).To(ContainSubstring(tc.wantLog))
			}
			if tc.wantNoOutput {
				Expect(strings.TrimSpace(result.stdout)).To(BeEmpty())
				return
			}

			got := decodeClaudeHookOutput(ginkgo.GinkgoT(), result.stdout)
			Expect(got).To(Equal(tc.wantCommand))
		},
		ginkgo.Entry("codebuddy missing cmdshape",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "cmdshape-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"pwd"}}`, wantLog: "skip-no-cmdshape", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy empty input",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "cmdshape-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log")},
			hookCase{input: "", withCmdshape: true, wantLog: "skip-empty-input", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy missing command",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "cmdshape-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{}}`, withCmdshape: true, wantLog: "skip-no-command", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy already prefixed",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "cmdshape-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"cmdshape pwd"}}`, withCmdshape: true, wantLog: "skip-no-change", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy rewrite",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "cmdshape-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "cmdshape-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"git status && ls"}}`, withCmdshape: true, wantCommand: "cmdshape git status && cmdshape ls"},
		),
	)

	ginkgo.Describe("CodeBuddy settings helpers", func() {
		var (
			tmpDir   string
			settings string
			hook     string
		)

		ginkgo.BeforeEach(func() {
			tmpDir = ginkgo.GinkgoT().TempDir()
			settings = filepath.Join(tmpDir, codebuddySettingsName)
			hook = filepath.Join(tmpDir, codebuddyHookScriptName)
		})

		ginkgo.It("removes the settings file when persisting an empty root", func() {
			Expect(os.WriteFile(settings, []byte("{}\n"), 0o644)).To(Succeed())

			changed, err := persistJSONSettings(settings, map[string]any{})
			Expect(err).NotTo(HaveOccurred())
			Expect(changed).To(BeTrue())
			_, err = os.Stat(settings)
			Expect(err).To(MatchError(os.ErrNotExist))
		})

		ginkgo.It("detects the managed CodeBuddy hook in settings", func() {
			escapedHook := strings.ReplaceAll(hook, "\\", "\\\\")
			content := "{\n  \"hooks\": {\n    \"PreToolUse\": [\n      {\n        \"matcher\": \"Bash\",\n        \"hooks\": [\n          {\n            \"type\": \"command\",\n            \"command\": \"" + escapedHook + "\"\n          }\n        ]\n      }\n    ]\n  }\n}\n"
			Expect(os.WriteFile(settings, []byte(content), 0o644)).To(Succeed())

			ok, err := codebuddySettingsUseHook(settings, hook)
			Expect(err).NotTo(HaveOccurred())
			Expect(ok).To(BeTrue())
		})

		ginkgo.It("returns marshal errors when settings contain unsupported values", func() {
			changed, err := persistJSONSettings(settings, map[string]any{
				"hooks": map[string]any{
					"PreToolUse": make(chan int),
				},
			})

			Expect(err).To(HaveOccurred())
			Expect(changed).To(BeFalse())
		})

		ginkgo.It("returns write errors when the settings path is a symlink", func() {
			target := filepath.Join(tmpDir, "outside-settings.json")
			Expect(os.WriteFile(target, []byte("{}\n"), 0o644)).To(Succeed())
			if err := os.Symlink(target, settings); err != nil {
				ginkgo.Skip("symlink creation unavailable: " + err.Error())
			}

			changed, err := persistJSONSettings(settings, map[string]any{
				"hooks": map[string]any{
					"PreToolUse": []any{},
				},
			})

			Expect(err).To(HaveOccurred())
			Expect(changed).To(BeFalse())
		})

		ginkgo.DescribeTable("matching managed CodeBuddy pre-tool-use hooks",
			func(pre []any, hookPath string, expected bool) {
				Expect(codebuddyPreToolUseContains(pre, hookPath)).To(Equal(expected))
			},
			ginkgo.Entry("matches bash command hooks", []any{
				map[string]any{
					"matcher": "Bash",
					"hooks": []any{
						map[string]any{"type": "command", "command": filepath.Join("tmp", codebuddyHookScriptName)},
					},
				},
			}, filepath.Join("tmp", codebuddyHookScriptName), true),
			ginkgo.Entry("ignores non-bash matchers", []any{
				map[string]any{
					"matcher": "Python",
					"hooks": []any{
						map[string]any{"type": "command", "command": filepath.Join("tmp", codebuddyHookScriptName)},
					},
				},
			}, filepath.Join("tmp", codebuddyHookScriptName), false),
			ginkgo.Entry("ignores non-command hook entries", []any{
				map[string]any{
					"matcher": "Bash",
					"hooks": []any{
						map[string]any{"type": "shell", "command": filepath.Join("tmp", codebuddyHookScriptName)},
					},
				},
			}, filepath.Join("tmp", codebuddyHookScriptName), false),
		)
	})
})
