package agents

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("hook settings family", func() {
	type hookScript struct {
		name       string
		scriptName string
		logName    string
		content    string
	}

	type hookCase struct {
		input        string
		withCCP      bool
		wantLog      string
		wantCommand  string
		wantNoOutput bool
	}

	ginkgo.DescribeTable("rendering canonical hook guidance",
		func(name string, content string, needles []string) {
			for _, needle := range needles {
				Expect(content).To(ContainSubstring(needle), name)
			}
		},
		ginkgo.Entry("codebuddy", "codebuddy", bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log"), []string{
			"generated by ccp init for codebuddy",
			"rewrite shell commands to use ccp",
			"ccp auto-rewrite",
			`LOG_FILE="${TMPDIR:-/tmp}/ccp-codebuddy-hook.log"`,
		}),
	)

	ginkgo.DescribeTable("executing managed hook scripts",
		func(script hookScript, tc hookCase) {
			result := runHookScript(ginkgo.GinkgoT(), script.scriptName, script.logName, script.content, tc.input, tc.withCCP)
			Expect(result.exitCode).To(Equal(0), result.stderr)

			if tc.wantLog != "" {
				Expect(result.log).To(ContainSubstring(tc.wantLog))
			}
			if tc.wantNoOutput {
				Expect(strings.TrimSpace(result.stdout)).To(BeEmpty())
				return
			}

			got := decodeClaudeHookOutput(ginkgo.GinkgoT(), result.stdout)
			Expect(got).To(Equal(tc.wantCommand))
		},
		ginkgo.Entry("codebuddy missing ccp",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "ccp-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"pwd"}}`, wantLog: "skip-no-ccp", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy empty input",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "ccp-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log")},
			hookCase{input: "", withCCP: true, wantLog: "skip-empty-input", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy missing command",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "ccp-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{}}`, withCCP: true, wantLog: "skip-no-command", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy already prefixed",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "ccp-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"ccp pwd"}}`, withCCP: true, wantLog: "skip-no-change", wantNoOutput: true},
		),
		ginkgo.Entry("codebuddy rewrite",
			hookScript{name: "codebuddy", scriptName: codebuddyHookScriptName, logName: "ccp-codebuddy-hook.log", content: bashRewriteHookScriptContent("codebuddy", "ccp-codebuddy-hook.log")},
			hookCase{input: `{"tool_input":{"command":"pwd && ls"}}`, withCCP: true, wantCommand: "ccp pwd && ccp ls"},
		),
	)

	ginkgo.Describe("CodeBuddy settings helpers", func() {
		var (
			tmpDir   string
			settings string
			hook     string
		)

		ginkgo.BeforeEach(func() {
			tmpDir = ginkgo.GinkgoT().TempDir()
			settings = filepath.Join(tmpDir, codebuddySettingsName)
			hook = filepath.Join(tmpDir, codebuddyHookScriptName)
		})

		ginkgo.It("detects the managed CodeBuddy hook in settings", func() {
			escapedHook := strings.ReplaceAll(hook, "\\", "\\\\")
			content := "{\n  \"hooks\": {\n    \"PreToolUse\": [\n      {\n        \"matcher\": \"Bash\",\n        \"hooks\": [\n          {\n            \"type\": \"command\",\n            \"command\": \"" + escapedHook + "\"\n          }\n        ]\n      }\n    ]\n  }\n}\n"
			Expect(os.WriteFile(settings, []byte(content), 0o644)).To(Succeed())

			ok, err := codebuddySettingsUseHook(settings, hook)
			Expect(err).NotTo(HaveOccurred())
			Expect(ok).To(BeTrue())
		})
	})
})
