package agents

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
)

const (
	legacyRuleSignature      = "Use `ccp` as the command prefix for every executable in shell commands"
	legacyHookSignature      = "# generated by ccp init for "
	legacyPluginSignature    = `return segment.slice(0, start) + "ccp "`
	legacyAwarenessSignature = "# CCP Integration"
	legacyJSPluginName       = "ccp-rewrite.js"
	legacyHookName           = "ccp-rewrite.sh"
)

// HasLegacyArtifacts reports whether the tool has a pre-rename managed
// contribution. It prevents startup migration from installing integrations
// that the user never enabled.
func HasLegacyArtifacts(ctx Context, tool string) bool {
	paths := legacyPrimaryArtifactPaths(ctx, NormalizeToolID(tool))
	if len(paths) == 0 {
		paths = legacySecondaryArtifactPaths(ctx, NormalizeToolID(tool))
	}
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err == nil && legacyArtifactContent(string(raw)) {
			return true
		}
	}
	return false
}

func legacyPrimaryArtifactPaths(ctx Context, tool string) []string {
	switch tool {
	case string(AgentAmazonQ):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, ".amazonq/rules/ccp.md")}
	case string(AgentCline):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, ".clinerules/ccp.md")}
	case string(AgentCursor):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, ".cursor/rules/ccp.mdc")}
	case string(AgentRooCode):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, ".roo/rules/ccp.md")}
	case string(AgentTrae):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, ".trae/rules/ccp.md")}
	case string(AgentWindsurf):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, ".windsurf/rules/ccp.md")}
	case string(AgentOpenCode):
		return []string{filepath.Join(managedJSPluginConfigRoot(ctx, "opencode"), "plugins", legacyJSPluginName)}
	case string(AgentKilocode):
		return []string{filepath.Join(managedJSPluginConfigRoot(ctx, "kilocode"), "plugins", legacyJSPluginName)}
	case string(AgentClaude):
		root := claudeRoot(ctx)
		return []string{
			filepath.Join(root, "hooks", legacyHookName),
			filepath.Join(root, "CCP.md"),
			filepath.Join(root, claudeGuideName),
		}
	case string(AgentCodeBuddy):
		return []string{filepath.Join(codebuddyRoot(ctx), "hooks", legacyHookName)}
	default:
		return nil
	}
}

func legacySecondaryArtifactPaths(ctx Context, tool string) []string {
	switch tool {
	case string(AgentAider):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, aiderRulesPath)}
	case string(AgentAuggie):
		return []string{ResolveRepoScopedPath(ctx.ScopeRoot, auggieAgentsPath)}
	case string(AgentAntigravity), string(AgentGemini):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, geminiInstructionsPath)}
	case string(AgentCodex):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, codexAgentsPath)}
	case string(AgentFactory):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, factoryAgentsPath)}
	case string(AgentGitHubCopilot):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, githubCopilotInstructionsPath)}
	case string(AgentKiro):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, kiroSteeringPath)}
	case string(AgentPi):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, ".pi/APPEND_SYSTEM.md")}
	case string(AgentQoder):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, qoderAgentsPath)}
	case string(AgentCrush):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, crushContextRelPath)}
	case string(AgentQwen):
		return []string{ResolveHomeScopedPath(ctx.HomeDir, qwenAgentsPath)}
	default:
		return nil
	}
}

func legacyArtifactContent(content string) bool {
	return strings.Contains(content, legacyManagedBlockStart) ||
		strings.Contains(content, legacyRuleSignature) ||
		strings.Contains(content, legacyHookSignature) ||
		strings.Contains(content, legacyPluginSignature) ||
		strings.Contains(content, legacyAwarenessSignature)
}

// CleanupLegacyArtifacts removes only files and settings contributions owned
// by the pre-rename integration after their cmdshape replacements verify.
func CleanupLegacyArtifacts(ctx Context, tools []string) error {
	var cleanupErrors []error
	for _, tool := range tools {
		switch NormalizeToolID(tool) {
		case string(AgentAmazonQ):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveRepoScopedPath(ctx.ScopeRoot, ".amazonq/rules/ccp.md"),
				legacyRuleSignature,
			))
		case string(AgentCline):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveRepoScopedPath(ctx.ScopeRoot, ".clinerules/ccp.md"),
				legacyRuleSignature,
			))
		case string(AgentCursor):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveRepoScopedPath(ctx.ScopeRoot, ".cursor/rules/ccp.mdc"),
				legacyRuleSignature,
			))
		case string(AgentRooCode):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveHomeScopedPath(ctx.HomeDir, ".roo/rules/ccp.md"),
				legacyRuleSignature,
			))
		case string(AgentTrae):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveRepoScopedPath(ctx.ScopeRoot, ".trae/rules/ccp.md"),
				legacyRuleSignature,
			))
		case string(AgentWindsurf):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				ResolveRepoScopedPath(ctx.ScopeRoot, ".windsurf/rules/ccp.md"),
				legacyRuleSignature,
			))
		case string(AgentOpenCode):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				filepath.Join(managedJSPluginConfigRoot(ctx, "opencode"), "plugins", legacyJSPluginName),
				legacyPluginSignature,
			))
		case string(AgentKilocode):
			cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
				filepath.Join(managedJSPluginConfigRoot(ctx, "kilocode"), "plugins", legacyJSPluginName),
				legacyPluginSignature,
			))
		case string(AgentClaude):
			cleanupErrors = append(cleanupErrors, cleanupLegacyHookIntegration(
				claudeRoot(ctx),
				legacyHookName,
				"CCP.md",
			)...)
		case string(AgentCodeBuddy):
			cleanupErrors = append(cleanupErrors, cleanupLegacyHookIntegration(
				codebuddyRoot(ctx),
				legacyHookName,
				"",
			)...)
		}
	}
	return errors.Join(cleanupErrors...)
}

// CleanupRetiredLegacyArtifacts removes managed contributions created by
// integrations that are no longer registered by cmdshape.
func CleanupRetiredLegacyArtifacts(ctx Context) error {
	continueRoot := filepath.Join(ctx.HomeDir, ".continue")
	cleanupErrors := cleanupLegacyHookIntegration(
		continueRoot,
		legacyHookName,
		"",
	)

	iflowPath := filepath.Join(ctx.HomeDir, ".iflow", "IFLOW.md")
	updated, changed, removeAll, err := removeManagedContextBlock(iflowPath)
	if err != nil {
		cleanupErrors = append(cleanupErrors, err)
	} else if changed {
		_, applyErr := applyManagedFileChange(iflowPath, updated, true, removeAll)
		cleanupErrors = append(cleanupErrors, applyErr)
	}
	return errors.Join(cleanupErrors...)
}

func cleanupLegacyHookIntegration(root, hookName, awarenessName string) []error {
	hookPath := filepath.Join(root, "hooks", hookName)
	settingsPath := filepath.Join(root, "settings.json")
	var cleanupErrors []error
	if _, err := removePreToolUseCommandHook(settingsPath, hookPath); err != nil {
		cleanupErrors = append(cleanupErrors, err)
	}
	cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(hookPath, legacyHookSignature))
	if awarenessName != "" {
		cleanupErrors = append(cleanupErrors, removeOwnedLegacyFile(
			filepath.Join(root, awarenessName),
			legacyAwarenessSignature,
		))
	}
	return cleanupErrors
}

func removeOwnedLegacyFile(path, signature string) error {
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.Contains(string(raw), signature) {
		return nil
	}
	return os.Remove(path)
}
